<?php
/*
Extract a list of French words from a special XML file and output them sorted,
one word per line (UTF-8 encoded).

The source file may be retrieved in UTF-8 encoding from the page:
http://infolingu.univ-mlv.fr/DonneesLinguistiques/Dictionnaires/telechargement.html
http://infolingu.univ-mlv.fr/DonneesLinguistiques/Dictionnaires/dela-fr-public-u8-xml.zip
*/

$source = file_get_contents($argv[1]);
preg_match_all("!<(form|lemma)>([\p{L}'’-]+)</(form|lemma)>!u", $source, $words);

// The source must be corrected because it uses 'oe' instead of 'œ'.
$oeligs = [
    "acœle",
    "acœlomate",
    "alstrœmeria",
    "amœbicide",
    "amphicœle",
    "blastocœle",
    "bœhmite",
    "bœuf",
    "brachyœsophage",
    "chœur",
    "cœlentéré",
    "cœliaque",
    "cœliochirurgie",
    "cœlioscopie",
    "cœlomate",
    "cœlome",
    "cœlomique",
    "cœlosomien",
    "cœlostat",
    "cœlurosaure",
    "cœnonympha",
    "cœnure",
    "cœnurose",
    "cœur",
    "cœursage",
    "cœurse",
    "consœur",
    "contrecœur",
    "Delbœuf",
    "désœuvré",
    "désœuvrement",
    "dianthœcia",
    "dicrocœliose",
    "diœstrus",
    "dryocœtes",
    "écœurant",
    "écœurement",
    "écœurer",
    "endamœbidé",
    "entamœba",
    "éthinylœstradiol",
    "fœtal",
    "fœtalisation",
    "fœticide",
    "fœtida",
    "fœto",
    "fœtologie",
    "fœtopathie",
    "fœtoscope",
    "fœtoscopie",
    "fœtus",
    "frambœsia",
    "frœbélien",
    "grœnendael",
    "gymnamœbien",
    "hyperœstrogénie",
    "hypoœstrogénie",
    "lagerstrœmia",
    "lœss",
    "lœssique",
    "lymphœdème",
    "manœuvrabilité",
    "manœuvrable",
    "manœuvrant",
    "manœuvre",
    "manœuvrer",
    "manœuvrier",
    "mégaœsophage",
    "melanorhœa",
    "mœritherium",
    "mœurs",
    "monœcie",
    "multicœur",
    "myxœdémateux",
    "myxœdème",
    "nœud",
    "œchslé",
    "œconomicus",
    "œcophylle",
    "œcuménicité",
    "œcuménique",
    "œcuménisme",
    "œcuméniste",
    "œdémateux",
    "œdématier",
    "œdème",
    "œdicnème",
    "œdipe",
    "œdipianisation",
    "œdipien",
    "œdipode",
    "œdogonium",
    "œdomètre",
    "œdométrie",
    "œdométrique",
    "œil",
    "œillade",
    "œillé",
    "œillère",
    "œillères",
    "œillet",
    "œilleton",
    "œilletonnage",
    "œilletonner",
    "œillette",
    "œnanthe",
    "œnanthique",
    "œneis",
    "œnilisme",
    "œnochoé",
    "œnocyte",
    "œnologie",
    "œnologique",
    "œnologue",
    "œnomètre",
    "œnométrie",
    "œnométrique",
    "œnophile",
    "œnotechnie",
    "œnothèque",
    "œnothéracée",
    "œnothère",
    "œrsted",
    "œsophage",
    "œsophagectomie",
    "œsophagien",
    "œsophagite",
    "œsophagoplastie",
    "œsophagoscope",
    "œsophagoscopie",
    "œsophagostomie",
    "œsophagotomie",
    "œstradiol",
    "œstral",
    "œstrane",
    "œstre",
    "œstridé",
    "œstriol",
    "œstrogène",
    "œstrogénique",
    "œstrogénothérapie",
    "œstrone",
    "œstroprogestatif",
    "œstrose",
    "œstrus",
    "œuf",
    "œufrier",
    "œufs",
    "œuvé",
    "œuvre",
    "œuvrer",
    "œuvres",
    "œuvrette",
    "phœnix",
    "pœcilandrie",
    "pœcile",
    "pœciliidé",
    "pœcilitique",
    "pœcilogynie",
    "pœcilotherme",
    "pœcilothermie",
    "polyœstrus",
    "pomœrium",
    "préœdipien",
    "rancœur",
    "rhœadale",
    "rœsti",
    "sœur",
    "sœurette",
    "stilbœstrol",
    "stœchiométrie",
    "stœchiométrique",
    "synœcisme",
    "ternstrœmiacée",
    "thécamœbien",
    "vœu",
    "vœux",
];

$allWords = [];
foreach ($words[2] as $word) {
    $word = str_replace('\\', '', $word);
    $subWords = explode(' ', str_replace(["'", "’", "-"], ' ', $word));

    foreach ($subWords as $subWord) {
        if (strpos($subWord, 'oe') >= 0) {
            foreach($oeligs as $oelig) {
                $incorrect = str_replace('œ', 'oe', $oelig);
                $subWord = str_replace($incorrect, $oelig, $subWord);
                if (strpos($subWord, 'oe') === false) break;
            }
        }
        $allWords[] = $subWord;
    }
}

$allWords = array_unique($allWords);
sort($allWords);
print(implode("\n", $allWords));